# Generated by Django 5.2.14 on 2026-06-06 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('APPLICATION_RECEIVED', 'Application Received'), ('APPLICATION_STATUS_CHANGED', 'Application Status Changed'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_UPDATED', 'Interview Updated'), ('RESCHEDULE_REQUESTED', 'Reschedule Requested'), ('RESCHEDULE_ACCEPTED', 'Reschedule Accepted'), ('RESCHEDULE_REJECTED', 'Reschedule Rejected'), ('GENERAL', 'General')], default='GENERAL', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
