# Generated by Django 5.2.14 on 2026-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('APPLICATION_RECEIVED', 'Application Received'), ('APPLICATION_STATUS_CHANGED', 'Application Status Changed'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_UPDATED', 'Interview Updated'), ('RESCHEDULE_REQUESTED', 'Reschedule Requested'), ('RESCHEDULE_ACCEPTED', 'Reschedule Accepted'), ('RESCHEDULE_REJECTED', 'Reschedule Rejected'), ('MESSAGE_RECEIVED', 'Message Received'), ('GENERAL', 'General')], default='GENERAL', max_length=50),
        ),
    ]
