# Generated by Django 5.2.14 on 2026-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('APPLICATION_RECEIVED', 'Application Received'), ('APPLICATION_STATUS_CHANGED', 'Application Status Changed'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_UPDATED', 'Interview Updated'), ('RESCHEDULE_REQUESTED', 'Reschedule Requested'), ('RESCHEDULE_ACCEPTED', 'Reschedule Accepted'), ('RESCHEDULE_REJECTED', 'Reschedule Rejected'), ('MESSAGE_RECEIVED', 'Message Received'), ('POST_LIKED', 'Post Liked'), ('POST_COMMENTED', 'Post Commented'), ('POST_REPOSTED', 'Post Reposted'), ('POST_SHARED_VIA_DM', 'Post Shared via DM'), ('GENERAL', 'General')], default='GENERAL', max_length=50),
        ),
    ]
