# Generated by Django 5.2.14 on 2026-06-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_received_welcome_email',
            field=models.BooleanField(default=False),
        ),
    ]
