# Generated by Django 5.2.14 on 2026-06-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('WELCOME', 'Welcome'), ('PASSWORD_RESET', 'Password Reset'), ('INTERVIEW_REMINDER', 'Interview Reminder'), ('APPLICATION_FOLLOW_UP', 'Application Follow Up'), ('APPLICATION_STATUS_CHANGED', 'Application Status Changed')], max_length=30),
        ),
    ]
