# Generated by Django 5.2.14 on 2026-06-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0002_alter_emaillog_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('WELCOME', 'Welcome'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification'), ('INTERVIEW_REMINDER', 'Interview Reminder'), ('APPLICATION_FOLLOW_UP', 'Application Follow Up'), ('APPLICATION_STATUS_CHANGED', 'Application Status Changed')], max_length=30),
        ),
    ]
