# Generated by Django 5.2.14 on 2026-06-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feed_posts/'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
