# Generated by Django 5.2.14 on 2026-06-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='certificates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='cv_language_preference',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='include_profile_photo_in_cv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='work_experience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
