# Generated by Django 5.2.14 on 2026-06-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_profiles', '0002_developerprofile_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='is_open_to_work',
            field=models.BooleanField(default=False),
        ),
    ]
