# Generated by Django 5.2.14 on 2026-06-09 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('feed_posts', '0003_postcomment_postlike_postrepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_shares', to='feed_posts.feedpost'),
        ),
    ]
