# Generated by Django 5.2.14 on 2026-06-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='is_hiring',
            field=models.BooleanField(default=False),
        ),
    ]
